In [1]:
import tensorflow as tf

**Creating a simple constant in Tensorflow**

In [55]:
t1 = tf.constant([1,5])

In [56]:
t1

<tf.Tensor 'Const_9:0' shape=(2,) dtype=int32>

In [68]:
t2 = tf.constant(([1,3,3],[2,3,2]))

**Creating a multidimensional array in Tensorflow**

In [69]:
t1.shape

TensorShape([Dimension(2)])

In [70]:
t2.shape

TensorShape([Dimension(2), Dimension(3)])

In [71]:
t3 = tf.reshape(t2,[3,2])

**A print statement**

In [72]:
model = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(model)
    print(session.run(t2))
    print(session.run(t3))

[[1 3 3]
 [2 3 2]]
[[1 3]
 [3 2]
 [3 2]]


In [73]:
t3.shape

TensorShape([Dimension(3), Dimension(2)])

In [74]:

with tf.Session() as session:
    session.run(model)
    print(session.run(tf.matmul(t2,t3)))

[[19 15]
 [17 16]]


In [64]:
t4 = tf.constant([1,5])

In [66]:
with tf.Session() as session:
    session.run(model)
    print(session.run(tf.tensordot(t1,t4,1)))

26
